### ISSUE TITLE
transfer name on npm

### ISSUE THREAD

**Issue by calvinmetcalf** [my-archives/pbkdf2#5]
it doesn't look like there is much active development on this module,  We've been doing a lot of work on the browserify version of the crypto module including it's [pbkdf2 implementation](https://github.com/crypto-browserify/pbkdf2-compat), currently [pbkdf2-compat on npm](https://npmjs.org/pbkdf2-compat). How would you feel about transferring over the npm package name for use with that project.  We would put a note in the readme to tell current users and would bump the major version.  

If you don't feel comfortable transferring it or plan to continue developing this module it's totally understandable if you don't want to, just thought it was worth an ask.

**Comment by fundon** [comment]
Hi @calvinmetcalf, sorry to reply so late.

I'm interesting your work and nice projects.
So I can transfer this project to `https://github.com/crypto-browserify`. 
How do you think?

**Comment by calvinmetcalf** [comment]
Thanks! You don't need to transfer the repo, just the name on NPM, you can run the command

``` bash
npm owner add cwmma pbkdf2
```

**Comment by fundon** [comment]
@calvinmetcalf Added

**Comment by calvinmetcalf** [comment]
thank you!

**Comment by fundon** [comment]
done!
