### ISSUE TITLE
Constant-time string comparison

### ISSUE THREAD

**Issue by shaunc** [my-archives/pbkdf2#6]
Perhaps something like this would be good to include:

Adapted from [here](https://crackstation.net/hashing-security.htm#slowequals).

```
function slowEquals(a, b) {
  var diff, mlen, i;
  diff = a.length ^ b.length;
  mlen = Math.min(a.length, b.length);
  for (i = 0; i <= mlen; i += 1) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
};
```

**Comment by fundon** [comment]
Thanks, nice article. I consider that.

**Comment by fundon** [comment]
Hi, see https://github.com/crypto-browserify/pbkdf2
